version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: nestjs-backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_SSL=${DB_SSL}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - '3001:80'
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
